# On branch push, download the windows testing bundle build and run it.

name: cardano-wallet Windows Tests

on:
  push:
    branches:
      - master
      - bors/staging
      - bors/trying
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  tests:
    runs-on: windows-2016
    name: Run tests on Windows
    if: '!github.event.pull_request || (github.event.pull_request.draft == false)'
    steps:
      - name: 'Wait for Hydra build'
        uses: rvl/hydra-build-products-action@master
        id: hydra
        with:
          hydra: 'https://hydra.iohk.io'
          jobs: 'cardano-wallet-tests-win64'
      - name: 'Fetch Windows testing bundle'
        shell: powershell
        run: |
          $output = "cardano-wallet-tests-win64.zip"
          Invoke-WebRequest -Uri ${{ steps.hydra.outputs.buildProducts }} -OutFile $output
          Expand-Archive -LiteralPath $output -DestinationPath .
          Get-ChildItem
      - name: 'cardano-wallet-core:unit'
        run: '.\\cardano-wallet-core-test-unit.exe --color'
      - name: 'cardano-wallet:unit'
        run: '.\\cardano-wallet-test-unit.exe --color'
      - name: 'cardano-wallet-cli:unit'
        run: '.\\cardano-wallet-cli-test-unit.exe --color'
      - name: 'text-class:unit'
        run: '.\\text-class-test-unit.exe --color'
      - name: 'cardano-wallet-launcher:unit'
        run: '.\\cardano-wallet-launcher-test-unit.exe --color'
        continue-on-error: true
      - name: 'cardano-wallet:integration'
        run: '.\\cardano-wallet-test-integration.exe --color'
        timeout-minutes: 60

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Advance windows-tests-pass and all-tests-pass branches"
        if: contains(github.ref, 'master')
        shell: bash
        run: 'bash .buildkite/push-branch.sh windows-tests-pass linux-tests-pass all-tests-pass'
        env:
          ACTIONS_SSH_KEY: "${{ secrets.ACTIONS_SSH_KEY }}"
